const LEWAM_API_BASE='https://8de13ef8-ab04-4bef-bf86-752f49a8c6e9-prod.e1-us-east-azure.choreoapis.dev/lewam/lewam/v1.0';
let selected={name:'Ye-Buna Creator Pro',amount:500},currentSubscriptionId=null,isMandateAuthorized=false,walletIsEmpty=false,simulationRunning=false;
const $=s=>document.querySelector(s),toast=m=>{const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3200)};
const event=(name,detail='',failure=false)=>{const box=$('#events');if(box.querySelector('.empty'))box.innerHTML='';const row=document.createElement('div');row.className='event'+(failure?' failure':'');row.innerHTML=`<b>${name}</b><span>${detail}</span><time>${new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</time>`;box.prepend(row)};
async function api(path,options={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10000);try{const response=await fetch(`${LEWAM_API_BASE}${path}`,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options,signal:controller.signal});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error?.message||data?.message||`Request failed (${response.status})`);return data}finally{clearTimeout(timer)}}
function busy(button,on,label){button.disabled=on;button.textContent=on?'Working…':label}
function subscriptionId(sub){return sub?.id||sub?.subscription?.id||sub?.data?.id||null}
function renderLadder(sub){const d=sub?.dunning?.data||sub?.dunning?.history||[];d.slice(-3).forEach((item,i)=>{const rung=document.querySelectorAll('.ladder-item')[i+1];if(!rung)return;rung.classList.add('failure');rung.querySelector('span').textContent=`Failed · ${item.error_code||item.provider_code||'40401'}`})}
function render(sub){if(!sub)return;currentSubscriptionId=subscriptionId(sub)||currentSubscriptionId;const status=sub.status||'active',period=sub.current_period_end||sub.currentPeriodEnd||'Pending';$('#enroll-state').textContent=`${status} · ${currentSubscriptionId}`;$('#renew-state').textContent=status==='active'?'Ready to renew':status;const card=document.querySelector('.hero-card');let details=card.querySelector('.subscription-details');if(!details){details=document.createElement('div');details.className='subscription-details';card.append(details)}details.innerHTML=`<div class="mini-row"><span>Subscription</span><b class="mono">${currentSubscriptionId||'—'}</b></div><div class="mini-row"><span>Mandate</span><b class="mono">${sub.mandate_id||sub.mandateId||'—'}</b></div><div class="mini-row"><span>Period end</span><b>${period}</b></div>`;renderLadder(sub);if(status==='canceled')event('subscription.canceled','Max retries exceeded',true)}
async function refresh(){if(!currentSubscriptionId)return null;const sub=await api(`/v1/subscriptions/${currentSubscriptionId}`);render(sub);return sub}
async function createLiveSubscription(){const sub=await api('/v1/subscriptions',{method:'POST',body:JSON.stringify({phone:$('#phone').value,name:$('#customer').value,plan_name:selected.name,amount:selected.amount*100})});currentSubscriptionId=subscriptionId(sub);if(!currentSubscriptionId)throw Error('The API returned no subscription ID');isMandateAuthorized=true;render(sub);event('subscription.active',currentSubscriptionId);return sub}
async function failRenewal(){try{return await api(`/v1/test/subscriptions/${currentSubscriptionId}/renew`,{method:'POST',body:JSON.stringify({simulate_failure:true,error_code:'40401'})})}catch(error){if(/40401|insufficient|past_due/i.test(error.message))return {status:'past_due',error_code:'40401'};throw error}}
async function advanceRetry(){for(const path of [`/v1/test/subscriptions/${currentSubscriptionId}/retry-now`,`/v1/test/subscriptions/${currentSubscriptionId}/travel`]){try{return await api(path,{method:'POST'})}catch(error){if(!/404|not found/i.test(error.message))throw error}}throw Error('No retry advance endpoint is available')}
async function loadHealth(){try{const health=await api('/v1/health'),caps=await api('/v1/capabilities'),telebirr=caps.data?.find(x=>x.provider==='telebirr');if(health.status==='healthy'&&telebirr?.recurring_supported){const badge=document.querySelector('.top-actions .live-dot');badge.innerHTML='<i></i> Engine online · production';badge.title=`SQLite ${health.database}`}}catch(error){document.querySelector('.top-actions .live-dot').textContent='Engine unavailable';toast(error.message)}}
document.querySelectorAll('.plan').forEach(plan=>plan.onclick=()=>{document.querySelectorAll('.plan').forEach(x=>x.classList.remove('selected'));plan.classList.add('selected');selected={name:plan.dataset.name,amount:Number(plan.dataset.amount)};$('#modal-amount').textContent=`${selected.amount.toLocaleString()} ETB`});
$('#authorize').onclick=()=>$('#modal').classList.add('open');$('#close').onclick=()=>$('#modal').classList.remove('open');
$('#confirm').onclick=async()=>{if($('#pin').value.length!==6)return toast('Enter a 6-digit demo PIN');const button=$('#confirm');busy(button,true);try{$('#modal').classList.remove('open');await createLiveSubscription();toast('Live subscription created')}catch(error){event('subscription.create_failed',error.message,true);toast(error.message)}finally{busy(button,false,'Confirm mandate')}};
$('#renew').onclick=async()=>{if(!currentSubscriptionId)return toast('Create a live subscription first');const button=$('#renew');busy(button,true);try{const renewal=await api(`/v1/test/subscriptions/${currentSubscriptionId}/renew`,{method:'POST'});document.querySelectorAll('#checklist div').forEach((row,i)=>{row.classList.add('done');row.querySelector('span').textContent=i===1?(renewal.invoiceId||'Paid in Full'):'Succeeded ✓'});event('charge.succeeded',renewal.invoiceId||'Silent debit');await refresh();toast('Live renewal completed')}catch(error){event('charge.failed',error.message,true);toast(error.message)}finally{busy(button,false,'Fast-forward to Day 30 ↗')}};
$('#funds').onclick=()=>{walletIsEmpty=$('#funds').classList.toggle('on');$('#funds').setAttribute('aria-pressed',walletIsEmpty);toast(walletIsEmpty?'Empty wallet enabled':'Empty wallet disabled')};
$('#retry').onclick=async()=>{if(!currentSubscriptionId)return toast('Create a live subscription first');if(!walletIsEmpty)return toast('Enable Empty Wallet first');const button=$('#retry');busy(button,true);try{const current=await refresh();if(current?.status==='active'){await failRenewal();event('charge.failed','Telebirr · error 40401',true)}await advanceRetry();const updated=await refresh();const status=updated?.status||'past_due';event(status==='canceled'?'subscription.canceled':'dunning.retry_scheduled',status==='canceled'?'Max retries exceeded':`status ${status}`,true);toast(status==='canceled'?'Subscription canceled after max retries':'Retry advanced')}catch(error){event('dunning.failed',error.message,true);toast(error.message)}finally{busy(button,false,'Fast-forward to next retry date')}};
$('#topup').onclick=async()=>{if(!currentSubscriptionId)return toast('Create a live subscription first');const button=$('#topup');busy(button,true);try{await api(`/v1/subscriptions/${currentSubscriptionId}/recover`,{method:'POST'});walletIsEmpty=false;$('#funds').classList.remove('on');await refresh();event('subscription.recovered',currentSubscriptionId);toast('Subscription recovered')}catch(error){event('recovery.failed',error.message,true);toast(error.message)}finally{busy(button,false,'Top up wallet & recover')}};
async function simulateLifecycle(){if(simulationRunning)return;simulationRunning=true;const button=$('#autoplay');busy(button,true);try{if(!currentSubscriptionId){$('#phone').value='0911223344';$('#customer').value='Hanna Tesfaye';await createLiveSubscription()}await new Promise(r=>setTimeout(r,2000));await $('#renew').onclick();await new Promise(r=>setTimeout(r,2000));if(!walletIsEmpty)$('#funds').click();for(let i=0;i<3;i++){await new Promise(r=>setTimeout(r,2000));await $('#retry').onclick()}toast('Simulation complete — full subscription lifecycle demonstrated.')}catch(error){toast(error.message)}finally{simulationRunning=false;busy(button,false,'▶ Simulate in 3 min')}}
$('#autoplay').onclick=simulateLifecycle;$('#reset').onclick=()=>location.reload();loadHealth();
