const API='https://8de13ef8-ab04-4bef-bf86-752f49a8c6e9-prod.e1-us-east-azure.choreoapis.dev/lewam/lewam/v1.0';
let selected={name:'Ye-Buna Creator Pro',amount:500},subId=null,retryStep=0;
const $=s=>document.querySelector(s),toast=m=>{const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)};
function event(name,detail=''){const box=$('#events');if(box.querySelector('.empty'))box.innerHTML='';const d=document.createElement('div');const bad=/failed|canceled|cancelled|40401/i.test(name+' '+detail);d.className='event'+(bad?' failure':'');d.innerHTML=`<b>${name}</b><span>${detail}</span><time>${new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</time>`;box.prepend(d);if(name==='dunning.retry_scheduled'&&/Attempt 3/.test(detail))event('subscription.canceled','Max retries exceeded')}
async function call(path,body){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),2500);try{const r=await fetch(API+'/v1'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:controller.signal});if(!r.ok)throw Error('API '+r.status);return await r.json()}catch(e){toast('Engine unavailable, continuing in safe simulation mode');return null}finally{clearTimeout(timer)}}
document.querySelectorAll('.plan').forEach(p=>p.onclick=()=>{document.querySelectorAll('.plan').forEach(x=>x.classList.remove('selected'));p.classList.add('selected');selected={name:p.dataset.name,amount:Number(p.dataset.amount)};$('#modal-amount').textContent=selected.amount.toLocaleString()+' ETB'});
$('#authorize').onclick=()=>$('#modal').classList.add('open');$('#close').onclick=()=>$('#modal').classList.remove('open');
$('#confirm').onclick=async()=>{if($('#pin').value.length!==6)return toast('Enter any 6 digits for the demo PIN');$('#modal').classList.remove('open');$('#authorize').disabled=true;const phone=$('#phone').value,name=$('#customer').value;event('customer.created',name);await call('/products',{name:selected.name});await call('/prices',{unit_amount:selected.amount,currency:'ETB',recurring:{interval:'month'}});await call('/customers',{name,phone});await call('/payment-methods',{provider:'telebirr',phone});const r=await call('/subscriptions',{customer:{name,phone},price:{amount:selected.amount},payment_method:{provider:'telebirr'}});subId=r?.id||'sub_demo_'+Math.random().toString(36).slice(2,9);event('mandate.authorized','Telebirr · 199183');event('subscription.active',subId);event('invoice.created',selected.amount+' ETB');$('#enroll-state').textContent='Mandate active';$('#renew-state').textContent='Ready to renew';$('#renew-state').classList.remove('muted');toast('Mandate authorized. Ready for Day 30.');$('#authorize').disabled=false};
$('#renew').onclick=async()=>{if(!subId)return toast('Authorize a mandate first');await call('/test/subscriptions/'+subId+'/renew',{});event('charge.succeeded','Silent debit · '+selected.amount+' ETB');event('invoice.paid','Period rolled forward');$('#renew-state').textContent='Renewal succeeded';$('#renew-state').classList.remove('muted');document.querySelectorAll('#checklist div').forEach((x,i)=>setTimeout(()=>{x.classList.add('done');x.querySelector('span').textContent='Succeeded ✓'},i*180));toast('Day 30 renewal completed');};
$('#funds').onclick=()=>{$('#funds').classList.toggle('on');$('#funds').setAttribute('aria-pressed',$('#funds').classList.contains('on'));toast($('#funds').classList.contains('on')?'40401 failure mode enabled':'Failure mode disabled')};
$('#retry').onclick=()=>{if(!subId)return toast('Complete enrollment first');retryStep=Math.min(3,retryStep+1);document.querySelectorAll('.ladder-item').forEach((x,i)=>x.classList.toggle('done',i<retryStep));$('#dunning-state').textContent=retryStep===3?'Final retry scheduled':'Retry '+retryStep+' scheduled';event('dunning.retry_scheduled','Attempt '+retryStep+' · '+[1,3,7][retryStep-1]+' day');toast('Retry ladder advanced')};$('#topup').onclick=()=>{retryStep=0;document.querySelectorAll('.ladder-item').forEach(x=>x.classList.remove('done'));event('charge.succeeded','Wallet recovered');$('#dunning-state').textContent='Recovered';toast('Wallet topped up. Subscription recovered.')};
$('#reset').onclick=()=>location.reload();$('#autoplay').onclick=()=>{if(!subId){$('#modal').classList.add('open');toast('Authorize the mandate, then continue the simulation')}else $('#renew').click()};
const retryButton=$('#retry');retryButton.onclick=async()=>{if(!subId)return toast('Complete enrollment first');if(!$('#funds').classList.contains('on'))return toast('Enable insufficient funds first');retryStep=Math.min(3,retryStep+1);const items=document.querySelectorAll('.ladder-item');items.forEach((x,i)=>{x.classList.toggle('failure',i===retryStep);x.classList.toggle('done',i<retryStep);if(i===retryStep){x.querySelector('span').textContent='Failed · error 40401';x.querySelector('strong').textContent=i===3?'+7 day retry · final attempt':x.querySelector('strong').textContent}});$('#dunning-state').textContent=retryStep===3?'Canceled after max retries':'Past due · retry '+retryStep+' scheduled';event('dunning.retry_scheduled','Attempt '+retryStep+' · '+[1,3,7][retryStep-1]+' day');toast(retryStep===3?'Final +7 day attempt reached. Subscription canceled.':'Payment failed. Retry scheduled.')};
