const LEWAM_API_BASE='https://8de13ef8-ab04-4bef-bf86-752f49a8c6e9-prod.e1-us-east-azure.choreoapis.dev/lewam/lewam/v1.0';
let selected={name:'Ye-Buna Creator Pro',amount:500},currentSubscriptionId=null,isMandateAuthorized=false,walletIsEmpty=false,simulationRunning=false,lastSubscription={};
const $=s=>document.querySelector(s),toast=m=>{const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3200)};
const event=(name,detail='',failure=false)=>{const box=$('#events'),stamp=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),key=`${name}|${detail}|${stamp}`;if([...box.querySelectorAll('.event')].some(row=>row.dataset.eventKey===key))return;if(box.querySelector('.empty'))box.innerHTML='';const row=document.createElement('div');row.className='event'+(failure?' failure':'');row.dataset.eventKey=key;row.innerHTML=`<b>${name}</b><span>${detail}</span><time>${stamp}</time>`;box.prepend(row)};
async function api(path,options={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10000);try{const response=await fetch(`${LEWAM_API_BASE}${path}`,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options,signal:controller.signal});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error?.message||data?.message||`Request failed (${response.status})`);return data}finally{clearTimeout(timer)}}
function busy(button,on,label){button.disabled=on;button.setAttribute('aria-busy',String(on));button.textContent=on?'⟳ Working…':label}
function bodyOf(value){return value?.subscription||value?.data||value||{}}
function subscriptionId(value){return bodyOf(value).id||null}
function retryText(value){return value?.nextRetryAt||value?.next_retry_at||'+1 day'}
function renderLadder(value){const sub=bodyOf(value),items=sub?.dunning?.data||sub?.dunning?.history||[],rungs=document.querySelectorAll('.ladder-item');rungs.forEach((rung,i)=>{rung.classList.remove('failure');const span=rung.querySelector('span');if(span)span.textContent=i===0?'Waiting for renewal':i===1?'+1 day retry':i===2?'+3 day retry':'+7 day retry'});items.slice(-4).forEach((item,index)=>{const attempt=Number(item.attempt||item.retry_attempt||index+1),rung=rungs[Math.min(attempt,3)];if(!rung)return;rung.classList.add('failure');const span=rung.querySelector('span');if(span)span.textContent=`Failed · ${item.error_code||item.failure_code||item.provider_code||'40401'}`});const attempt=Number(sub.attempt||sub.retry_attempt||value?.attempt||0);if(attempt){const rung=rungs[Math.min(attempt,3)];if(rung){rung.classList.add('failure');const span=rung.querySelector('span');if(span)span.textContent=attempt>=4?'Canceled · max retries exceeded':`Failed · 40401 · next ${retryText(value)}`}}}
function render(value){const incoming=bodyOf(value);if(!incoming)return;const sub={...lastSubscription,...incoming};lastSubscription=sub;currentSubscriptionId=subscriptionId(value)||currentSubscriptionId;const status=sub.status||value?.status||'active',period=sub.current_period_end||sub.currentPeriodEnd||value?.current_period_end||'Pending';$('#enroll-state').textContent=`${status} · ${currentSubscriptionId}`;$('#renew-state').textContent=status==='active'?'Ready to renew':status;const card=document.querySelector('.hero-card');let details=card.querySelector('.subscription-details');if(!details){details=document.createElement('div');details.className='subscription-details';card.append(details)}details.innerHTML=`<div class="mini-row"><span>Subscription</span><b class="mono">${currentSubscriptionId||'—'}</b></div><div class="mini-row"><span>Mandate</span><b class="mono">${sub.mandate_id||sub.mandateId||'—'}</b></div><div class="mini-row"><span>Period end</span><b>${period}</b></div>`;renderLadder({...sub,...value})}
async function refresh(){if(!currentSubscriptionId)return null;const sub=await api(`/v1/subscriptions/${currentSubscriptionId}`);render(sub);return sub}
async function createLiveSubscription(){const sub=await api('/v1/subscriptions',{method:'POST',body:JSON.stringify({phone:$('#phone').value,name:$('#customer').value,plan_name:selected.name,amount:selected.amount*100})});currentSubscriptionId=subscriptionId(sub);if(!currentSubscriptionId)throw Error('The API returned no subscription ID');isMandateAuthorized=true;render(sub);event('subscription.active',currentSubscriptionId);return sub}
async function failRenewal(){return api(`/v1/test/subscriptions/${currentSubscriptionId}/renew`,{method:'POST',body:JSON.stringify({simulate_failure:true,error_code:'40401'})})}
async function advanceRetry(){return api(`/v1/test/subscriptions/${currentSubscriptionId}/retry-now`,{method:'POST',body:JSON.stringify({simulate_failure:walletIsEmpty===true,error_code:'40401'})})}
async function loadHealth(){try{const health=await api('/v1/health'),caps=await api('/v1/capabilities'),telebirr=caps.data?.find(x=>x.provider==='telebirr');if(health.status==='healthy'&&telebirr?.recurring_supported){const badge=document.querySelector('.top-actions .live-dot');badge.innerHTML='<i></i> Engine online · production';badge.title=`SQLite ${health.database}`}}catch(error){document.querySelector('.top-actions .live-dot').textContent='Engine unavailable';toast(error.message)}}
document.querySelectorAll('.plan').forEach(plan=>plan.onclick=()=>{document.querySelectorAll('.plan').forEach(x=>x.classList.remove('selected'));plan.classList.add('selected');selected={name:plan.dataset.name,amount:Number(plan.dataset.amount)};$('#modal-amount').textContent=`${selected.amount.toLocaleString()} ETB`});
$('#authorize').onclick=()=>$('#modal').classList.add('open');$('#close').onclick=()=>$('#modal').classList.remove('open');
$('#confirm').onclick=async()=>{if($('#pin').value.length!==6)return toast('Enter a 6-digit demo PIN');const button=$('#confirm');busy(button,true);try{$('#modal').classList.remove('open');await createLiveSubscription();toast('Live subscription created')}catch(error){event('subscription.create_failed',error.message,true);toast(error.message)}finally{busy(button,false,'Confirm mandate')}};
$('#renew').onclick=async()=>{if(!currentSubscriptionId)return toast('Create a live subscription first');const button=$('#renew');busy(button,true);try{const renewal=await api(`/v1/test/subscriptions/${currentSubscriptionId}/renew`,{method:'POST'});document.querySelectorAll('#checklist div').forEach((row,i)=>{row.classList.add('done');row.querySelector('span').textContent=i===1?(renewal.invoiceId||renewal.invoice_id||'Paid in Full'):'Succeeded ✓'});event('charge.succeeded',renewal.invoiceId||renewal.invoice_id||'Silent debit');await refresh();toast('Live renewal completed')}catch(error){event('charge.failed',error.message,true);toast(error.message)}finally{busy(button,false,'Fast-forward to Day 30 ↗')}};
$('#funds').onclick=()=>{walletIsEmpty=$('#funds').classList.toggle('on');$('#funds').setAttribute('aria-pressed',walletIsEmpty);toast(walletIsEmpty?'Empty wallet enabled':'Empty wallet disabled')};
$('#retry').onclick=async()=>{if(!currentSubscriptionId)return toast('Create a live subscription first');if(!walletIsEmpty)return toast('Enable Empty Wallet first');const button=$('#retry');busy(button,true);try{const current=await refresh();let result;if(current?.status==='active'){result=await failRenewal();render(result);event('charge.failed','Telebirr · error 40401',true);event('dunning.retry_scheduled',`Attempt ${result.attempt||1} · next ${retryText(result)}`,true);toast('Payment failed · past_due · retry scheduled')}else{result=await advanceRetry();render(result);const status=bodyOf(result).status||result.status||'past_due';if(status==='canceled'){event('subscription.canceled','Max retries exceeded',true);toast('Subscription canceled after max retries')}else{event('dunning.retry_scheduled',`Attempt ${result.attempt||'next'} · next ${retryText(result)}`,true);toast('Retry advanced · still past_due')}}}catch(error){event('dunning.failed',error.message,true);toast(error.message)}finally{busy(button,false,'Fast-forward to next retry date')}};
$('#topup').onclick=async()=>{if(!currentSubscriptionId)return toast('Create a live subscription first');const button=$('#topup');busy(button,true);try{await api(`/v1/subscriptions/${currentSubscriptionId}/recover`,{method:'POST'});walletIsEmpty=false;$('#funds').classList.remove('on');await refresh();event('subscription.recovered',currentSubscriptionId);toast('Subscription recovered')}catch(error){event('recovery.failed',error.message,true);toast(error.message)}finally{busy(button,false,'Top up wallet & recover')}};
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function simulateLifecycle(){if(simulationRunning)return;simulationRunning=true;const button=$('#autoplay');busy(button,true);try{if(!currentSubscriptionId){$('#phone').value='0911223344';$('#customer').value='Hanna Tesfaye';await createLiveSubscription()}await wait(2000);await $('#renew').onclick();await wait(2000);if(!walletIsEmpty)$('#funds').click();for(let attempt=1;attempt<=4;attempt++){await wait(2000);await $('#retry').onclick()}toast('Simulation complete — full subscription lifecycle demonstrated.')}catch(error){toast(error.message)}finally{simulationRunning=false;busy(button,false,'▶ Simulate in 3 min')}}
$('#autoplay').onclick=simulateLifecycle;$('#reset').onclick=()=>location.reload();loadHealth();
